[metadata]
name = "dirs"
description = "Find directories (fd)"
requirements = ["fd"]

[source]
command = ["fd -t d", "fd -t d --hidden"]

[preview]
command = "eza -la --color=always '{}'"

[keybindings]
shortcut = "f2"
enter = "actions:cd"

[actions.cd]
description = "Open shell in directory"
command = "cd '{}' && $SHELL"
mode = "execute"

[ui.preview_panel]
hidden = true
